#!/bin/bash

############################################################
# Triticale genome-wide pairwise alignment (ZX830 vs PT)
# Subgenomes: A / B / R
############################################################

# maximum parallel jobs
max_jobs=9

function wait_for_jobs() {
  while [ "$(jobs -p | wc -l)" -ge "$max_jobs" ]; do
    sleep 1
  done
}

############################################################
# samples
############################################################

samples=("ZX830" "PT")

############################################################
# subgenomes
############################################################

subgenomes=("A" "B" "R")

############################################################
# main loop
############################################################

for sample in "${samples[@]}"; do

  mkdir -p ${sample}

  for i in {1..7}; do
    for j in {1..7}; do
      for x in "${subgenomes[@]}"; do
        for y in "${subgenomes[@]}"; do

          wait_for_jobs

          ref=/data1/public/triticale/${samples[0]}/${samples[0]}.chr${i}${x}.fa
          qry=/data1/public/triticale/${sample}/${sample}.chr${j}${y}.fa

          nucmer \
            -p ${sample}_chr${i}${x}_chr${j}${y} \
            --maxgap=500 \
            --mincluster=1000 \
            "$ref" "$qry" &

        done
      done
    done
  done

done

wait
